version: 2
# log-file: "/Users/danc/.local/share/nvim/efm.log"
# log-level: 1
root-markers:
  - .git/
  - Cargo.toml
  - pyproject.toml
  - setup.py
  - package.json
tools:
  python-black: &python-black
    format-command: 'black -'
    format-stdin: true

  python-isort: &python-isort
    format-command: 'isort --stdout -'
    format-stdin: true

  python-flake8: &python-flake8
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  python-mypy: &python-mypy
    lint-command: 'mypy --show-column-numbers'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  markdown-pandoc: &markdown-pandoc
    format-command: 'pandoc -f markdown -t gfm -sp --tab-stop=2'

  rst-pandoc: &rst-pandoc
    format-command: 'pandoc -f rst -t rst -s --columns=79'

  yaml-yamllint: &yaml-yamllint
    lint-command: 'yamllint -f parsable -'
    lint-stdin: true

  sh-shellcheck: &sh-shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  javascript-eslint: &javascript-eslint
    lint-command: 'eslint -f unix --stdin'
    lint-ignore-exit-code: true
    lint-stdin: true

  html-prettier: &html-prettier
    format-command: './node_modules/.bin/prettier --parser html'

  css-prettier: &css-prettier
    format-command: './node_modules/.bin/prettier --parser css'

  json-prettier: &json-prettier
    format-command: './node_modules/.bin/prettier --parser json'

  prettier: &prettier
    format-command: './node_modules/.bin/prettier'

  json-jq: &json-jq
    lint-command: 'jq .'

  toml-fmt: &toml-fmt
    format-command: 'toml-fmt'
    format-stdin: true

languages:
  python:
    - <<: *python-black
    - <<: *python-isort
    - <<: *python-flake8
    - <<: *python-mypy

  markdown:
    - <<: *markdown-pandoc

  # toml:
  #   - <<: *toml-fmt

  rst:
    - <<: *rst-pandoc

  yaml:
    - <<: *yaml-yamllint

  sh:
    - <<: *sh-shellcheck

  javascript:
    - <<: *prettier
    - <<: *javascript-eslint

  typescript:
    - <<: *prettier
    - <<: *javascript-eslint

  vue:
    - <<: *prettier
    - <<: *javascript-eslint

  html:
    - <<: *html-prettier

  css:
    - <<: *css-prettier

  json:
    - <<: *json-jq
    - <<: *json-prettier
